# Generated by Django 4.2.1 on 2023-05-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HH', 'Highest'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('LL', 'Lowest')], default='M'),
        ),
    ]
